# Generated by Django 4.1.7 on 2023-09-02 18:07

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedpacket',
            name='sip_info',
            field=djongo.models.fields.JSONField(),
        ),
    ]
