# Generated by Django 4.1.7 on 2023-09-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_analyzedpacket_sip_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzedPacket',
        ),
    ]
