# Generated by Django 4.1.7 on 2023-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_delete_analyzedpacket'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_identifier', models.CharField(max_length=100)),
                ('sip_info', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
